- name: Commit scan_results.json if changed
  run: |
    git add output/scan_results.json
    if git diff --cached --quiet; then
      echo "✅ No changes to commit."
    else
      git config user.name "github-actions[bot]"
      git config user.email "github-actions[bot]@users.noreply.github.com"
      git commit -m "Update scan results"
      git push
    fi
